routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

/* All Routed Related to the Dashboard*/
Route::group(['prefix' => '/dash', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {


    Route::get('/', ['as' => 'dashboard', 'uses' => 'Dashboard\HomeController@index']);
    Route::resource('notifications', 'Dashboard\NotificationController');

    Route::resource('institutes', 'Dashboard\InstituteController');
    Route::post('institutes/{id}/edit', 'Dashboard\InstituteController@update');
    Route::get('institutes/status/{type}/{id}', 'Dashboard\InstituteController@change_status')->name('institutes.status');
    Route::get('branch/status/{type}/{id}', 'Dashboard\BranchController@change_status')->name('branches.status');

    Route::resource('institute-manage-dashboard', 'Dashboard\ManageDashboardController');

    Route::resource('banners', 'Dashboard\BannerController');
    Route::resource('services', 'Dashboard\ServiceController');
    Route::resource('albums', 'Dashboard\AlbumController');


});

/* All Routed Related to the WebSite*/
Route::group(['prefix' => '/', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {

    Route::get('', ['as' => 'home', 'uses' => 'Website\HomeController@index']);

});

Route::get('lang/switcher/{type}', ['as' => 'lang.switcher', 'uses' => 'LanguageController@apply']);

app/Http/Controllers/Dashboard/AlbumController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Album;
use App\Models\Credential;
use App\Models\Gallery;
use App\Models\Service;
use App\Models\Owner;
use App\Models\Institute;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use App\Repositories\CurdRepository;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class AlbumController extends Controller
{
    protected $model;

    use General;

    public function __construct(Album $album)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($album);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Album::class);
        $pageTitle = __('album.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->paginate(12)
        ];
        return view('dashboard.albums.index', $viewParams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Album::class);

        $pageTitle = __('album.create');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
        ];

        return view('dashboard.albums.create', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Album::class);
        /*applied validations*/
        $request->validate([
            'name' => 'unique:albums,name',
            'name_ur' => 'unique:albums,name_ur'
        ]);
        $data = $request->only($this->model->getModel()->fillable);
        // Save the Detail of the Institute
        $this->model = $this->model->create($data);
        if ($this->model) {

            if ($request->file('album_avatar')) {

                //General trait function
                $this->makeMultipleDirectories('albums', ['avatars']);
                $avatar = $request->file('album_avatar');
                $avatar_name = sha1('img' . $this->model->id . time()) . '.' . $avatar->getClientOriginalExtension();
                $avatar = Image::make($avatar);
                $avatar->save(public_path('uploads/albums/avatars/') . $avatar_name);
                $this->model->avatar = $avatar_name;
                $this->model->save();

            }

            /* Ready to save the gallery images*/

            if ($request->file('galleries')) {
                $galleries = $request->file('galleries');
                $this->makeMultipleDirectories('albums', ['galleries']);
                $count = count($galleries);
                for ($i = 0; $i < $count; $i++) {

                    $gallery = $galleries[$i];

                    if ($gallery) {
                        $extension = $gallery->getClientOriginalExtension();
                        $gallery_avatar_name = sha1('img' . $this->model->id . time()) . '.' . $extension;
                        $gallery_avatar = Image::make($gallery);
                        $gallery_avatar->backup();
                        $gallery_avatar->save(public_path('uploads/albums/galleries/') . $gallery_avatar_name);
                        $this->model->galleries()->save(new Gallery([
                            'avatar' => $gallery_avatar_name
                        ]));
                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __('message.record_created_success_message')
            ]);

        } else {

            return response()->json([
                'status' => 404,
                'message' => __('message.record_created_failed_message')
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $this->authorize('edit', Institute::class);
        $this->model = $this->model->find($id);

        $pageTitle = __('btn.edit') . " " . $this->model->name;
        $breadcrumbs = [['text' => __('system.edit_venue')]];
        $viewParams = [
            'model' => $this->model,
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];

        return view('dashboard.institutes.edit', $viewParams);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     * @throws AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $this->authorize('edit', Institute::class);
        $request->validate([
            'name' => 'required|max:255|unique:institutes,name,' . $id,
            'name_ur' => 'required|max:255|unique:institutes,name_ur,' . $id,
        ]);
        $this->model->update($request->only($this->model->getModel()->fillable), $id);
        $this->model = $this->model->find($id);
        if ($this->model) {
            if ($request->file('avatar')) {
                $existing_image = public_path('uploads/institutes/') . $this->model->avatar;
                if (file_exists($existing_image)) {
                    unlink($existing_image);
                }
                $imageName = sha1('img' . $this->model->id . time()) . '.' . $request->file('avatar')->getClientOriginalExtension();
                $image = Image::make($request->file('avatar'));
                $image->backup();
                $image->save(public_path('uploads/institutes/') . $imageName);
                $this->model->avatar = $imageName;
                $this->model->save();
            }

            // Ready to save the owners
            if ($request->has('owners')) {
                $this->makeMultipleDirectories('institutes', ['owners']);
                $owners = $request->get('owners');
                $count = count($owners['name']);
                for ($i = 0; $i < $count; $i++) {

                    $existing_id = isset($owners['id'][$i]) ? $owners['id'][$i] : '';

                    if (!empty($existing_id)) {

                        $owner = Owner::find($existing_id);
                        $owner->name = $owners['name'][$i];
                        $owner->name_ur = $owners['name_ur'][$i];
                        $owner->save();

                    } else {

                        $owner = $this->model->owners()->save(
                            new Owner(
                                [
                                    'name' => $owners['name'][$i],
                                    'name_ur' => $owners['name_ur'][$i]
                                ]));
                    }

                    // ready to save & update the avatar of each owner

                    $owner_file = isset($request->file('owners')['avatar'][$i]) ? $request->file('owners')['avatar'][$i] : '';

                    if (!empty($owner_file)) {

                        $existing_image = public_path('uploads/institutes/owners/') . $owner->avatar;
                        if (!is_dir($existing_image) && file_exists($existing_image)) {
                            unlink($existing_image);
                        }
                        $extension = $owner_file->getClientOriginalExtension();
                        $owner_avatar_name = sha1('img' . $this->model->id . $owner->id . time()) . '.' . $extension;
                        $owner_image = Image::make($owner_file);
                        $owner_image->backup();
                        $owner_image->save(public_path('uploads/institutes/owners/') . $owner_avatar_name);
                        $owner->avatar = $owner_avatar_name;
                        $owner->save();

                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __($this->model->name . " " . __('message.record_updated_success_message'))
            ]);

        } else {

            // show error in case of error

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function destroy($id)
    {
        $this->authorize('delete', Institute::class);
        $this->model = $this->model->find($id);
        if ($this->model->delete($id)) {
            return redirect()->route('institutes.index')->with('errorMessage', $this->model->name . " " . __('message.deleted_successfully'));
        }
    }
}

app/Http/Controllers/Dashboard/BannerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Intervention\Image\Facades\Image;

class BannerController extends Controller
{
    protected $model;

    use General;

    public function __construct(Banner $banner)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($banner);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Banner::class);
        $pageTitle = __('banner.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->get()
        ];
        return view('dashboard.banners.index', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('edit', Banner::class);
        $input = $request->all();
        $length = count($input['heading']);
        $banner = null;
        for ($i = 0; $i < $length; $i++) {

            $heading = $input['heading'][$i];
            $heading_ur = $input['heading_ur'][$i];
            $active = isset($input['active'][$i]) ? 1 : 0;
            $data = [
                'heading' => $heading,
                'heading_ur' => $heading_ur,
                'active' => $active
            ];
            //save or update
            if (isset($input['id'][$i]) && !empty($input['id'][$i])) {

                $this->model->update($data, $input['id'][$i]);
                $banner = $this->model->find($input['id'][$i]);

                if (isset($request->file('image')[$i])) {
                    $removed_image = 'uploads/banners/images/' . $banner->image;
                    if (file_exists(public_path() . '/' . $removed_image) && !is_dir($removed_image)) {
                        unlink($removed_image);
                    }
                }

                if (isset($request->file('avatar')[$i])) {
                    $removed_avatar = 'uploads/banners/avatars/' . $banner->avatar;
                    if (file_exists(public_path() . '/' . $removed_avatar) && !is_dir($removed_avatar)) {
                        unlink($removed_avatar);
                    }
                }

            } else {

                $banner = $this->model->create($data);

            }

            if (isset($request->file('image')[$i])) {
                $image = $request->file('image')[$i];
                $this->makeDirectory('banners/images');
                $extension = $image->getClientOriginalExtension();
                $image_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $image = Image::make($image);
                $image->backup();
                $image->save(public_path('uploads/banners/images/') . $image_name);
                $banner->image = $image_name;
                $banner->save();
            }

            if (isset($request->file('avatar')[$i])) {
                $avatar = $request->file('avatar')[$i];
                $this->makeDirectory('banners/avatars');
                $extension = $avatar->getClientOriginalExtension();
                $avatar_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $avatar = Image::make($avatar);
                $avatar->backup();
                $avatar->save(public_path('uploads/banners/avatars/') . $avatar_name);
                $banner->avatar = $avatar_name;
                $banner->save();

            }

        }

        return redirect()->route('banners.index');
    }
}

app/Http/Controllers/Dashboard/BranchController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    protected $model;

    use General;

    public function __construct(Branch $branch)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($branch);
    }

    public function change_status($type, $id)
    {
        $this->model = $this->model->find($id);
        if ($this->model) {
            switch ($type) {
                case "active":
                    $this->model->active = false;
                    break;
                case  "in_active":
                    $this->model->active = true;
                    break;
            }
            $this->model->save();
            return response()->json([
                'type' => $type
            ]);
        }
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $pageTitle = __('dashboard.welcome_back');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];
        return view('dashboard.index', $viewParams);
    }
}

resources/views/dashboard/albums/edit.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)

@section('styleInnerFiles')
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap-select/dist/css/bootstrap-select.min.css') }}">
@endsection

@section('breadcrumbs')
    @include('partials.dashboard.breadcrumbs', ['pageTitle' => $pageTitle,'breadcrumbs' => $breadcrumbs])
@stop

@section('content')
    <div class="card card-solid">
        @can('read',\App\Models\User::class)
            <div class="card-header">
                <div class="card-title">
                    {!! link_to_route('venues.index',__('system.all_venues'),null,['class'=>'btn btn-info btn-sm']) !!}
                </div>
            </div>
        @endcan
        <div class="card-body pb-0">
            <!-- form start -->
            {!! Form::model($model, ['route' => ['venues.update', $model], 'method' => 'PUT','files' => true] ) !!}
            {!! csrf_field() !!}
            @include('partials.dashboard.message')

            <div class="form-group">
                {!! Form::label('venue_owner', 'Assign Owner') !!}
                {!! Form::select('user_id', $users, null, array('id' => 'venue_owner',
                'class' => 'form-control selectpicker show-menu-arrow', 'data-live-search' => 'true', 'data-selected-text-format' => 'count > 3',
                'data-size' => '10', 'data-actions-box' => 'true')) !!}
            </div>
            <div class="form-group">
                {!! Form::label('inputName', __('system.name')) !!}
                {!! Form::text('name', null, ['class' => 'form-control', 'autofocus','placeholder'=>__('system.placeholder_name'), 'id' => 'inputName' ]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('inputLocation', __('system.location')) !!}
                {!! Form::text('location', null, ['class' => 'form-control', 'id' => 'inputLocation','placeholder'=>__('system.placeholder_location') ]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('inputCapacity', __('system.capacity')) !!}
                {!! Form::text('capacity', null, ['class' => 'form-control', 'id' => 'inputCapacity','placeholder'=>__('system.placeholder_capacity') ]) !!}
            </div>
            <div class="form-group">
                {!! Form::label('avatar', 'Choose Avatar') !!}
                <div class="input-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="avatar" id="avatar" onchange="loadFile(event)">
                        <label class="custom-file-label" for="avatar">Choose Image</label>
                    </div>
                </div>
                <div class="p-3 text-center">
                    <img style="max-width: 100px;max-height: 100px;" src="{{ $model->getAvatar() }}">
                </div>
            </div>
            <div class="form-group">
                {!! Form::label('description', 'Description') !!}
                {!! Form::textarea('description', null, ['class' => 'form-control', 'rows' => 5, 'id' => 'description' ]) !!}
            </div>
            <div class="form-group icheck-success d-inline">
                {!! Form::checkbox('active', 1, true,['id'=>'inputActive']) !!}
                {!! Form::label('inputActive', __('system.is_active')) !!}
            </div>

            <div class="form-group text-right">
                {!! Form::submit(__('system.update'), array('class' => 'btn btn-primary pull-left btn-sm')) !!}
            </div>
            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('scriptInnerFiles')
    <script type="text/javascript"
            src="{{ asset('plugins/bootstrap-select/dist/js/bootstrap-select.min.js') }}"></script>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=o23blg9ah1zca8fzz4hpnqndoxanbov1pv288bvw0ptznp19"></script>
@stop
@section('pageScript')
    <script>
        var loadFile = function (event) {
            var reader = new FileReader();
            reader.onload = function () {
                $(event.target).closest('.form-group').find('img').attr('src', reader.result);
            };
            reader.readAsDataURL(event.target.files[0]);
        };
        $(function () {
            // Replace the textarea with tinyMCE
            tinymce.init({
                selector: '#description',
                height: 200,
                theme: 'modern'
            });
        });
    </script>
@endsection

resources/views/dashboard/albums/index.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)

@section('breadcrumbs')
    @include('partials.dashboard.breadcrumbs', ['pageTitle' => $pageTitle,'breadcrumbs' => $breadcrumbs])
@stop

@section('content')
    <div class="row">
        <div class="col-lg-12 col-12">
            <div class="card">
                <div class="card-header row align-items-center mx-1">
                    <div class="card-title col-xl-6 col-lg-6 col-md-6">
                        @can('create',\App\Models\Album::class)
                            {!! link_to_route('albums.create',__('album.create'),null,['class'=>'btn bg-gradient-primary btn-sm']) !!}
                        @endcan
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 text-right">
                        <form action="{{ route('albums.index') }}" method="get">
                            <div class="row justify-content-end">
                                <div class="col-xl-5">
                                    <select class="custom-select custom-select-sm" name="field">
                                        <option value="name" @if(isset($field) and $field == 'name') selected @endif>
                                            {{__('general.name')}}
                                        </option>
                                    </select>
                                </div>
                                <div class="col-xl-5">
                                    <input type="search" name="keyword"
                                           value="@if(isset($keyword) and $keyword != '') {{ $keyword }} @endif"
                                           class="form-control form-control-sm"
                                           placeholder="{{__('btn.search_here')}}">
                                </div>
                                <div class="col-xl-2">
                                    <input type="submit" class="btn btn-info btn-sm" value="{{ __('btn.filter') }}">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card-body">
                    @include('partials.dashboard.message')
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="text-center">{{__('general.avatar')}}</th>
                            <th>{{__('general.name')}}</th>
                            <th class="text-right">{{__('general.name_ur')}}</th>
                            <th class="text-center">{{__('general.is_active')}}</th>
                            <th class="text-center">{{__('general.galleries')}}</th>
                            <th class="text-center">{{ __('general.created_at') }}</th>
                            <th class="text-center">{{ __('general.last_modified') }}</th>
                            <th class="text-center">{{ __('general.action') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if(count($data)>0)
                            @foreach($data as $d)
                                <tr>
                                    <td class="text-center m-auto">
                                        <img class="img-circle img-thumbnail img-sm" src="{{$d->avatar()}}">
                                    </td>
                                    <td>{{$d->name}}</td>
                                    <td class="text-right">{{$d->name_ur}}</td>
                                    <td class="text-center">
                                        @if($d->active)
                                            <span class="badge badge-success">
                                                <i class="fa fa-check"></i>
                                            </span>
                                        @else
                                            <span class="badge badge-danger">
                                                <i class="fa fa-times"></i>
                                            </span>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @include('dashboard.albums.components.galleries')
                                    </td>
                                    <td class="text-center">{{$d->created_at}}</td>
                                    <td class="text-center">{{$d->updated_at->diffForHumans()}}</td>
                                    <td class="text-center">
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-default">Action</button>
                                            <button type="button" class="btn btn-default dropdown-toggle"
                                                    data-toggle="dropdown">
                                                <span class="caret"></span>
                                                <span class="sr-only">Toggle Dropdown</span>
                                            </button>
                                            <ul class="dropdown-menu" role="menu">
                                                @can('edit',\App\Models\Album::class)
                                                    <li class="dropdown-item">{!! link_to_route('albums.edit', __('btn.edit'), [$d->id]) !!}</li>
                                                @endif
                                                @can('delete',\App\Models\Album::class)
                                                    <form action="{{ route('albums.destroy',$d->id) }}"
                                                          method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <li class="dropdown-item">
                                                            <button type="submit" class="bg-transparent"
                                                                    onclick="return confirm('{{__('message.dou_you_really_wants_to_delete')}}')"
                                                                    style="border: none;padding-left: 0;color: #c13535;">
                                                                {{__('btn.delete')}}
                                                            </button>
                                                        </li>
                                                    </form>
                                                @endcan
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        @else
                            <tr class="text-center">
                                <td colspan="12" class="p-3">{{ __('message.no_record_found') }}</td>
                            </tr>
                        @endif
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    {{ $data->links() }}
                </div>
            </div>
        </div>
    </div>
@stop