routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

/* All Routed Related to the Dashboard*/
Route::group(['prefix' => '/dash', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {


    Route::get('/', ['as' => 'dashboard', 'uses' => 'Dashboard\HomeController@index']);
    Route::resource('notifications', 'Dashboard\NotificationController');

    Route::resource('institutes', 'Dashboard\InstituteController');
    Route::post('institutes/{id}/edit', 'Dashboard\InstituteController@update');
    Route::get('institutes/status/{type}/{id}', 'Dashboard\InstituteController@change_status')->name('institutes.status');
    Route::get('branch/status/{type}/{id}', 'Dashboard\BranchController@change_status')->name('branches.status');

    Route::resource('institute-manage-dashboard', 'Dashboard\ManageDashboardController');

    Route::resource('banners', 'Dashboard\BannerController');
    Route::resource('services', 'Dashboard\ServiceController');
    Route::resource('albums', 'Dashboard\AlbumController');


});

/* All Routed Related to the WebSite*/
Route::group(['prefix' => '/', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {

    Route::get('', ['as' => 'home', 'uses' => 'Website\HomeController@index']);

});

Route::get('lang/switcher/{type}', ['as' => 'lang.switcher', 'uses' => 'LanguageController@apply']);

app/Http/Controllers/Dashboard/AlbumController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Album;
use App\Models\Credential;
use App\Models\Gallery;
use App\Models\Service;
use App\Models\Owner;
use App\Models\Institute;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use App\Repositories\CurdRepository;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class AlbumController extends Controller
{
    protected $model;

    use General;

    public function __construct(Album $album)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($album);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Album::class);
        $pageTitle = __('album.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->paginate(12)
        ];
        return view('dashboard.albums.index', $viewParams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Album::class);

        $pageTitle = __('album.create');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
        ];

        return view('dashboard.albums.create', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Album::class);
        /*applied validations*/
        $request->validate([
            'name' => 'unique:albums,name',
            'name_ur' => 'unique:albums,name_ur'
        ]);
        $data = $request->only($this->model->getModel()->fillable);
        // Save the Detail of the Institute
        $this->model = $this->model->create($data);
        if ($this->model) {

            if ($request->file('album_avatar')) {

                //General trait function
                $this->makeMultipleDirectories('albums', ['avatars']);
                $avatar = $request->file('album_avatar');
                $avatar_name = sha1('img' . $this->model->id . time()) . '.' . $avatar->getClientOriginalExtension();
                $avatar = Image::make($avatar);
                $avatar->save(public_path('uploads/albums/avatars/') . $avatar_name);
                $this->model->avatar = $avatar_name;
                $this->model->save();

            }

            /* Ready to save the gallery images*/

            if ($request->file('galleries')) {
                $galleries = $request->file('galleries');
                $this->makeMultipleDirectories('albums', ['galleries']);
                $count = count($galleries);
                for ($i = 0; $i < $count; $i++) {

                    $gallery = $galleries[$i];

                    if ($gallery) {
                        $extension = $gallery->getClientOriginalExtension();
                        $gallery_avatar_name = sha1('img' . $this->model->id . time()) . '.' . $extension;
                        $gallery_avatar = Image::make($gallery);
                        $gallery_avatar->backup();
                        $gallery_avatar->save(public_path('uploads/albums/galleries/') . $gallery_avatar_name);
                        $this->model->galleries()->save(new Gallery([
                            'avatar' => $gallery_avatar_name
                        ]));
                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __('message.record_created_success_message')
            ]);

        } else {

            return response()->json([
                'status' => 404,
                'message' => __('message.record_created_failed_message')
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $this->authorize('edit', Institute::class);
        $this->model = $this->model->find($id);

        $pageTitle = __('btn.edit') . " " . $this->model->name;
        $breadcrumbs = [['text' => __('system.edit_venue')]];
        $viewParams = [
            'model' => $this->model,
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];

        return view('dashboard.institutes.edit', $viewParams);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     * @throws AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $this->authorize('edit', Institute::class);
        $request->validate([
            'name' => 'required|max:255|unique:institutes,name,' . $id,
            'name_ur' => 'required|max:255|unique:institutes,name_ur,' . $id,
        ]);
        $this->model->update($request->only($this->model->getModel()->fillable), $id);
        $this->model = $this->model->find($id);
        if ($this->model) {
            if ($request->file('avatar')) {
                $existing_image = public_path('uploads/institutes/') . $this->model->avatar;
                if (file_exists($existing_image)) {
                    unlink($existing_image);
                }
                $imageName = sha1('img' . $this->model->id . time()) . '.' . $request->file('avatar')->getClientOriginalExtension();
                $image = Image::make($request->file('avatar'));
                $image->backup();
                $image->save(public_path('uploads/institutes/') . $imageName);
                $this->model->avatar = $imageName;
                $this->model->save();
            }

            // Ready to save the owners
            if ($request->has('owners')) {
                $this->makeMultipleDirectories('institutes', ['owners']);
                $owners = $request->get('owners');
                $count = count($owners['name']);
                for ($i = 0; $i < $count; $i++) {

                    $existing_id = isset($owners['id'][$i]) ? $owners['id'][$i] : '';

                    if (!empty($existing_id)) {

                        $owner = Owner::find($existing_id);
                        $owner->name = $owners['name'][$i];
                        $owner->name_ur = $owners['name_ur'][$i];
                        $owner->save();

                    } else {

                        $owner = $this->model->owners()->save(
                            new Owner(
                                [
                                    'name' => $owners['name'][$i],
                                    'name_ur' => $owners['name_ur'][$i]
                                ]));
                    }

                    // ready to save & update the avatar of each owner

                    $owner_file = isset($request->file('owners')['avatar'][$i]) ? $request->file('owners')['avatar'][$i] : '';

                    if (!empty($owner_file)) {

                        $existing_image = public_path('uploads/institutes/owners/') . $owner->avatar;
                        if (!is_dir($existing_image) && file_exists($existing_image)) {
                            unlink($existing_image);
                        }
                        $extension = $owner_file->getClientOriginalExtension();
                        $owner_avatar_name = sha1('img' . $this->model->id . $owner->id . time()) . '.' . $extension;
                        $owner_image = Image::make($owner_file);
                        $owner_image->backup();
                        $owner_image->save(public_path('uploads/institutes/owners/') . $owner_avatar_name);
                        $owner->avatar = $owner_avatar_name;
                        $owner->save();

                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __($this->model->name . " " . __('message.record_updated_success_message'))
            ]);

        } else {

            // show error in case of error

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function destroy($id)
    {
        $this->authorize('delete', Institute::class);
        $this->model = $this->model->find($id);
        if ($this->model->delete($id)) {
            return redirect()->route('institutes.index')->with('errorMessage', $this->model->name . " " . __('message.deleted_successfully'));
        }
    }
}

app/Http/Controllers/Dashboard/BannerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Intervention\Image\Facades\Image;

class BannerController extends Controller
{
    protected $model;

    use General;

    public function __construct(Banner $banner)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($banner);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Banner::class);
        $pageTitle = __('banner.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->get()
        ];
        return view('dashboard.banners.index', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('edit', Banner::class);
        $input = $request->all();
        $length = count($input['heading']);
        $banner = null;
        for ($i = 0; $i < $length; $i++) {

            $heading = $input['heading'][$i];
            $heading_ur = $input['heading_ur'][$i];
            $active = isset($input['active'][$i]) ? 1 : 0;
            $data = [
                'heading' => $heading,
                'heading_ur' => $heading_ur,
                'active' => $active
            ];
            //save or update
            if (isset($input['id'][$i]) && !empty($input['id'][$i])) {

                $this->model->update($data, $input['id'][$i]);
                $banner = $this->model->find($input['id'][$i]);

                if (isset($request->file('image')[$i])) {
                    $removed_image = 'uploads/banners/images/' . $banner->image;
                    if (file_exists(public_path() . '/' . $removed_image) && !is_dir($removed_image)) {
                        unlink($removed_image);
                    }
                }

                if (isset($request->file('avatar')[$i])) {
                    $removed_avatar = 'uploads/banners/avatars/' . $banner->avatar;
                    if (file_exists(public_path() . '/' . $removed_avatar) && !is_dir($removed_avatar)) {
                        unlink($removed_avatar);
                    }
                }

            } else {

                $banner = $this->model->create($data);

            }

            if (isset($request->file('image')[$i])) {
                $image = $request->file('image')[$i];
                $this->makeDirectory('banners/images');
                $extension = $image->getClientOriginalExtension();
                $image_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $image = Image::make($image);
                $image->backup();
                $image->save(public_path('uploads/banners/images/') . $image_name);
                $banner->image = $image_name;
                $banner->save();
            }

            if (isset($request->file('avatar')[$i])) {
                $avatar = $request->file('avatar')[$i];
                $this->makeDirectory('banners/avatars');
                $extension = $avatar->getClientOriginalExtension();
                $avatar_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $avatar = Image::make($avatar);
                $avatar->backup();
                $avatar->save(public_path('uploads/banners/avatars/') . $avatar_name);
                $banner->avatar = $avatar_name;
                $banner->save();

            }

        }

        return redirect()->route('banners.index');
    }
}

app/Http/Controllers/Dashboard/BranchController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    protected $model;

    use General;

    public function __construct(Branch $branch)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($branch);
    }

    public function change_status($type, $id)
    {
        $this->model = $this->model->find($id);
        if ($this->model) {
            switch ($type) {
                case "active":
                    $this->model->active = false;
                    break;
                case  "in_active":
                    $this->model->active = true;
                    break;
            }
            $this->model->save();
            return response()->json([
                'type' => $type
            ]);
        }
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $pageTitle = __('dashboard.welcome_back');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];
        return view('dashboard.index', $viewParams);
    }
}

resources/views/dashboard/notifications/index.blade.php
@extends('layouts.dashboard')
@section('pageTitle', $pageTitle)
@section('breadcrumbs')
    @include('partials.dashboard.breadcrumbs')
@stop
@section('content')
    <section class="content">
        <div class="row">
            <div class="col-md-3">
                <a href="compose.html"
                   class="btn btn-primary btn-block mb-3">{{__('notification.generate_for_all')}}</a>
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">{{__('notification.folders')}}</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                    class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">
                            <li class="nav-item active">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-inbox"></i> {{__('notification.inbox')}}
                                    <span class="badge bg-primary float-right">12</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-envelope"></i> {{__('notification.sent')}}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-file-alt"></i> {{__('notification.draft')}}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-filter"></i> {{__('notification.junk')}}
                                    <span class="badge bg-warning float-right">65</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="far fa-trash-alt"></i> {{__('notification.trash')}}
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">{{__('notification.inbox')}}</h3>
                        <div class="card-tools">
                            <div class="input-group input-group-sm">
                                <input type="text" class="form-control" placeholder="{{__('notification.filter')}}">
                                <div class="input-group-append">
                                    <div class="btn btn-primary">
                                        <i class="fas fa-search"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                @if($data->count()>0)
                                    @foreach($data as $unreadNotification)
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" value="{{ $unreadNotification->id }}"
                                                           id="check-{{$unreadNotification->id}}">
                                                    <label for="check-{{$unreadNotification->id}}"></label>
                                                </div>
                                            </td>
                                            <td class="mailbox-name">
                                                <a href="{{ route('institutes.show',[$unreadNotification['data']['sender']]) }}">
                                                    {{ \App\Models\Institute::find($unreadNotification['data']['sender'])->name_ur }}
                                                </a>
                                            </td>
                                            <td class="mailbox-subject">
                                                {{ $unreadNotification['data']['message'] }}
                                            </td>
                                            <td class="mailbox-attachment"><i class="fas fa-paperclip"></i></td>
                                            <td class="mailbox-date">{{ $unreadNotification->created_at->diffForHumans() }}</td>
                                        </tr>
                                    @endforeach
                                @endif
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            {{ $data->links()  }}
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection