routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('auth/{provider}', 'Auth\RegisterController@redirectToProvider');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');
Route::get('auth/{provider}/callback', 'Auth\RegisterController@handleProviderCallback');

/* All Routed Related to the Dashboard*/
Route::group(['prefix' => '/dash', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {


    Route::get('/', ['as' => 'dashboard', 'uses' => 'Dashboard\HomeController@index']);
    Route::resource('notifications', 'Dashboard\NotificationController');

    Route::resource('institutes', 'Dashboard\InstituteController');
    Route::post('institutes/{id}/edit', 'Dashboard\InstituteController@update');
    Route::get('institutes/status/{type}/{id}', 'Dashboard\InstituteController@change_status')->name('institutes.status');
    Route::get('branch/status/{type}/{id}', 'Dashboard\BranchController@change_status')->name('branches.status');

    Route::resource('institute-manage-dashboard', 'Dashboard\ManageDashboardController');

    Route::resource('banners', 'Dashboard\BannerController');
    Route::resource('services', 'Dashboard\ServiceController');
    Route::resource('albums', 'Dashboard\AlbumController');


});

/* All Routed Related to the WebSite*/
Route::group(['prefix' => '/', 'middleware' => ['maintenance', 'permissions', 'localized']], function () {

    Route::get('', ['as' => 'home', 'uses' => 'Website\HomeController@index']);

});

Route::get('lang/switcher/{type}', ['as' => 'lang.switcher', 'uses' => 'LanguageController@apply']);

app/Http/Controllers/Dashboard/AlbumController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Album;
use App\Models\Credential;
use App\Models\Gallery;
use App\Models\Service;
use App\Models\Owner;
use App\Models\Institute;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use App\Repositories\CurdRepository;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class AlbumController extends Controller
{
    protected $model;

    use General;

    public function __construct(Album $album)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($album);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Album::class);
        $pageTitle = __('album.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->paginate(12)
        ];
        return view('dashboard.albums.index', $viewParams);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create', Album::class);

        $pageTitle = __('album.create');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
        ];

        return view('dashboard.albums.create', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Album::class);
        /*applied validations*/
        $request->validate([
            'name' => 'unique:albums,name',
            'name_ur' => 'unique:albums,name_ur'
        ]);
        $data = $request->only($this->model->getModel()->fillable);
        // Save the Detail of the Institute
        $this->model = $this->model->create($data);
        if ($this->model) {

            if ($request->file('album_avatar')) {

                //General trait function
                $this->makeMultipleDirectories('albums', ['avatars']);
                $avatar = $request->file('album_avatar');
                $avatar_name = sha1('img' . $this->model->id . time()) . '.' . $avatar->getClientOriginalExtension();
                $avatar = Image::make($avatar);
                $avatar->save(public_path('uploads/albums/avatars/') . $avatar_name);
                $this->model->avatar = $avatar_name;
                $this->model->save();

            }

            /* Ready to save the gallery images*/

            if ($request->file('galleries')) {
                $galleries = $request->file('galleries');
                $this->makeMultipleDirectories('albums', ['galleries']);
                $count = count($galleries);
                for ($i = 0; $i < $count; $i++) {

                    $gallery = $galleries[$i];

                    if ($gallery) {
                        $extension = $gallery->getClientOriginalExtension();
                        $gallery_avatar_name = sha1('img' . $this->model->id . time()) . '.' . $extension;
                        $gallery_avatar = Image::make($gallery);
                        $gallery_avatar->backup();
                        $gallery_avatar->save(public_path('uploads/albums/galleries/') . $gallery_avatar_name);
                        $this->model->galleries()->save(new Gallery([
                            'avatar' => $gallery_avatar_name
                        ]));
                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __('message.record_created_success_message')
            ]);

        } else {

            return response()->json([
                'status' => 404,
                'message' => __('message.record_created_failed_message')
            ]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function edit($id)
    {
        $this->authorize('edit', Institute::class);
        $this->model = $this->model->find($id);

        $pageTitle = __('btn.edit') . " " . $this->model->name;
        $breadcrumbs = [['text' => __('system.edit_venue')]];
        $viewParams = [
            'model' => $this->model,
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];

        return view('dashboard.institutes.edit', $viewParams);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     * @throws AuthorizationException
     */
    public function update(Request $request, $id)
    {
        $this->authorize('edit', Institute::class);
        $request->validate([
            'name' => 'required|max:255|unique:institutes,name,' . $id,
            'name_ur' => 'required|max:255|unique:institutes,name_ur,' . $id,
        ]);
        $this->model->update($request->only($this->model->getModel()->fillable), $id);
        $this->model = $this->model->find($id);
        if ($this->model) {
            if ($request->file('avatar')) {
                $existing_image = public_path('uploads/institutes/') . $this->model->avatar;
                if (file_exists($existing_image)) {
                    unlink($existing_image);
                }
                $imageName = sha1('img' . $this->model->id . time()) . '.' . $request->file('avatar')->getClientOriginalExtension();
                $image = Image::make($request->file('avatar'));
                $image->backup();
                $image->save(public_path('uploads/institutes/') . $imageName);
                $this->model->avatar = $imageName;
                $this->model->save();
            }

            // Ready to save the owners
            if ($request->has('owners')) {
                $this->makeMultipleDirectories('institutes', ['owners']);
                $owners = $request->get('owners');
                $count = count($owners['name']);
                for ($i = 0; $i < $count; $i++) {

                    $existing_id = isset($owners['id'][$i]) ? $owners['id'][$i] : '';

                    if (!empty($existing_id)) {

                        $owner = Owner::find($existing_id);
                        $owner->name = $owners['name'][$i];
                        $owner->name_ur = $owners['name_ur'][$i];
                        $owner->save();

                    } else {

                        $owner = $this->model->owners()->save(
                            new Owner(
                                [
                                    'name' => $owners['name'][$i],
                                    'name_ur' => $owners['name_ur'][$i]
                                ]));
                    }

                    // ready to save & update the avatar of each owner

                    $owner_file = isset($request->file('owners')['avatar'][$i]) ? $request->file('owners')['avatar'][$i] : '';

                    if (!empty($owner_file)) {

                        $existing_image = public_path('uploads/institutes/owners/') . $owner->avatar;
                        if (!is_dir($existing_image) && file_exists($existing_image)) {
                            unlink($existing_image);
                        }
                        $extension = $owner_file->getClientOriginalExtension();
                        $owner_avatar_name = sha1('img' . $this->model->id . $owner->id . time()) . '.' . $extension;
                        $owner_image = Image::make($owner_file);
                        $owner_image->backup();
                        $owner_image->save(public_path('uploads/institutes/owners/') . $owner_avatar_name);
                        $owner->avatar = $owner_avatar_name;
                        $owner->save();

                    }
                }
            }

            return response()->json([
                'status' => 200,
                'message' => __($this->model->name . " " . __('message.record_updated_success_message'))
            ]);

        } else {

            // show error in case of error

        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     * @throws AuthorizationException
     */
    public function destroy($id)
    {
        $this->authorize('delete', Institute::class);
        $this->model = $this->model->find($id);
        if ($this->model->delete($id)) {
            return redirect()->route('institutes.index')->with('errorMessage', $this->model->name . " " . __('message.deleted_successfully'));
        }
    }
}

app/Http/Controllers/Dashboard/BannerController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Banner;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Intervention\Image\Facades\Image;

class BannerController extends Controller
{
    protected $model;

    use General;

    public function __construct(Banner $banner)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($banner);
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     * @throws AuthorizationException
     */
    public function index(Request $request)
    {
        $this->authorize('read', Banner::class);
        $pageTitle = __('banner.title');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'field' => $request->query('field', null),
            'keyword' => $request->query('keyword', null),
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle,
            'data' => $this->model->all($request->all())->get()
        ];
        return view('dashboard.banners.index', $viewParams);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return void
     * @throws AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('edit', Banner::class);
        $input = $request->all();
        $length = count($input['heading']);
        $banner = null;
        for ($i = 0; $i < $length; $i++) {

            $heading = $input['heading'][$i];
            $heading_ur = $input['heading_ur'][$i];
            $active = isset($input['active'][$i]) ? 1 : 0;
            $data = [
                'heading' => $heading,
                'heading_ur' => $heading_ur,
                'active' => $active
            ];
            //save or update
            if (isset($input['id'][$i]) && !empty($input['id'][$i])) {

                $this->model->update($data, $input['id'][$i]);
                $banner = $this->model->find($input['id'][$i]);

                if (isset($request->file('image')[$i])) {
                    $removed_image = 'uploads/banners/images/' . $banner->image;
                    if (file_exists(public_path() . '/' . $removed_image) && !is_dir($removed_image)) {
                        unlink($removed_image);
                    }
                }

                if (isset($request->file('avatar')[$i])) {
                    $removed_avatar = 'uploads/banners/avatars/' . $banner->avatar;
                    if (file_exists(public_path() . '/' . $removed_avatar) && !is_dir($removed_avatar)) {
                        unlink($removed_avatar);
                    }
                }

            } else {

                $banner = $this->model->create($data);

            }

            if (isset($request->file('image')[$i])) {
                $image = $request->file('image')[$i];
                $this->makeDirectory('banners/images');
                $extension = $image->getClientOriginalExtension();
                $image_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $image = Image::make($image);
                $image->backup();
                $image->save(public_path('uploads/banners/images/') . $image_name);
                $banner->image = $image_name;
                $banner->save();
            }

            if (isset($request->file('avatar')[$i])) {
                $avatar = $request->file('avatar')[$i];
                $this->makeDirectory('banners/avatars');
                $extension = $avatar->getClientOriginalExtension();
                $avatar_name = sha1('img' . $banner->id . time()) . '.' . $extension;
                $avatar = Image::make($avatar);
                $avatar->backup();
                $avatar->save(public_path('uploads/banners/avatars/') . $avatar_name);
                $banner->avatar = $avatar_name;
                $banner->save();

            }

        }

        return redirect()->route('banners.index');
    }
}

app/Http/Controllers/Dashboard/BranchController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Branch;
use App\Repositories\CurdRepository;
use App\Traits\General;
use Illuminate\Http\Request;

class BranchController extends Controller
{
    protected $model;

    use General;

    public function __construct(Branch $branch)
    {
        $this->middleware('auth');
        // set the model
        $this->model = new CurdRepository($branch);
    }

    public function change_status($type, $id)
    {
        $this->model = $this->model->find($id);
        if ($this->model) {
            switch ($type) {
                case "active":
                    $this->model->active = false;
                    break;
                case  "in_active":
                    $this->model->active = true;
                    break;
            }
            $this->model->save();
            return response()->json([
                'type' => $type
            ]);
        }
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{

    public function __construct()
    {
        return $this->middleware('auth');
    }

    public function index()
    {
        $pageTitle = __('dashboard.welcome_back');
        $breadcrumbs = [['text' => $pageTitle]];
        $viewParams = [
            'breadcrumbs' => $breadcrumbs,
            'pageTitle' => $pageTitle
        ];
        return view('dashboard.index', $viewParams);
    }
}

resources/views/partials/dashboard/breadcrumbs.blade.php
<div class="content-header">
    <div class="container-fluid">
        <div class="row my-0 align-items-center">
            <div class="col-6">
                @if(isset($pageTitle) && $pageTitle != '')
                    <h5 class="m-0 text-dark font-weight-bold"> {{$pageTitle}} </h5>
                @endif
            </div><!-- /.col -->
            <div class="col-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a
                            href=" {{ route('dashboard',['lang'=>app()->getLocale()]) }}">{{__('dashboard.return-to-home')}}</a>
                    </li>
                    @foreach($breadcrumbs as $leaf)
                        @if(!empty($leaf['url']))
                            <li class="breadcrumb-item"><a href="{{$leaf['url']}}">{{$leaf['text']}}</a></li>
                        @else
                            <li class="breadcrumb-item active">{{$leaf['text']}}</li>
                        @endif
                    @endforeach
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

resources/views/partials/dashboard/control-sidebar.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/partials/dashboard/footer.blade.php
<footer class="main-footer">
    <strong>Copyright © 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.5
    </div>
</footer>

resources/views/partials/dashboard/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{ asset('dashboard/img/user1-128x128.jpg') }}" alt="User Avatar"
                             class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{ asset('dashboard/img/user8-128x128.jpg') }}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{ asset('dashboard/img/user3-128x128.jpg') }}" alt="User Avatar"
                             class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        {{-- Translator --}}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                {{(app()->getLocale()=="ur")?'اردو':'English'}}
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{route('lang.switcher',['ur'])}}">اردو</a>
                <a class="dropdown-item" href="{{route('lang.switcher',['en'])}}">English</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
                    class="fas fa-th-large"></i></a>
        </li>
    </ul>
</nav>

resources/views/partials/dashboard/left-bar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{{ asset('dashboard/img/AdminLTELogo.png') }}" alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">AdminLTE 3</span>
    </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ asset('dashboard/img/user2-160x160.jpg') }}" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{ route('notifications.index') }}" class="nav-link @if(strpos(request()->url(), 'notifications')) {{ 'active' }} @endif">
                        <i class="nav-icon fa fa-bell"></i>
                        <p>
                            {{ __('dashboard.notifications') }}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('services.index') }}" class="nav-link @if(strpos(request()->url(), 'services')) {{ 'active' }} @endif">
                        <i class="nav-icon fas fa-file-image"></i>
                        <p>
                            {{ __('dashboard.services') }}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('institutes.index') }}" class="nav-link @if(strpos(request()->url(), 'institutes')) {{ 'active' }} @endif">
                        <i class="nav-icon fas fa-building"></i>
                        <p>
                            {{ __('dashboard.institutes') }}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('banners.index') }}" class="nav-link @if(strpos(request()->url(), 'banners')) {{ 'active' }} @endif">
                        <i class="nav-icon fas fa-sliders-h"></i>
                        <p>
                            {{ __('dashboard.banners') }}
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('albums.index') }}" class="nav-link @if(strpos(request()->url(), 'albums')) {{ 'active' }} @endif">
                        <i class="nav-icon fa fa-image" aria-hidden="true"></i>
                        <p>
                            {{ __('dashboard.albums') }}
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

resources/views/partials/dashboard/message.blade.php
@if($errors->any())
    <div class="card-body">
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-ban"></i> Alert!</h5>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif

@if ($successMessage = \Illuminate\Support\Facades\Session::get('successMessage'))
    <div class="card-body">
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5><i class="icon fas fa-check"></i> {{__('system.alert')}}</h5>
            {{$successMessage}}
        </div>
    </div>
@endif

@if ($errorMessage = \Illuminate\Support\Facades\Session::get('errorMessage'))
    <div class="card-body">
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h5>{{__('system.alert')}}</h5>
            {{$errorMessage}}
        </div>
    </div>
@endif